/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AaSvgIcon: typeof import('./../src/components/icon/AaSvgIcon.vue')['default']
    AtIcon: typeof import('./../src/components/icon/AtIcon.vue')['default']
    GpIcon: typeof import('./../src/components/icon/GpIcon.vue')['default']
    Icon: typeof import('./../src/components/icon/Icon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NFlex: typeof import('naive-ui')['NFlex']
    SvgIcon: typeof import('./../src/components/icon/SvgIcon.vue')['default']
  }
}
